server:
  port: 8081
  servlet:
    context-path: /PhoneBook
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: 11111
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
